- name: deploy supervisor
  hosts: testserver
  become: True
  roles:
    - role: arillso.logrotate
  vars:
    filebeat_log_dir: /home/vagrant/apps/filebeat/logs
    node_exporter_log_dir: /home/vagrant/apps/node_exporter/logs
    logrotate_package: logrotate
    logrotate_use_hourly_rotation: true
    logrotate_include_dir: /etc/logrotate.d
    logrotate_applications:
      - name: youdong_logrotate
        definitions:
          - logs:
              - "{{ filebeat_log_dir }}/*.log"
              - "{{ node_exporter_log_dir }}/*.log"
            options:
              - su {{ ansible_user }} {{ ansible_user }}
              - size 50M
              - rotate 3
              - daily
              - missingok
              - notifempty
              - copytruncate
              - create 0644 vagrant vagrant
              - |
                  postrotate
                         killall filebeat
                         killall node_exporter
                      endscript
